export const dasarVariables = {
  font: {
    sans: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    hero: "'Space Grotesk', sans-serif",
  },
  fontWeight: {
    thin: '300',
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
  },
  fontSize: {
    xss: '0.5rem',
    xs: '0.625rem',
    sm: '0.75rem',
    base: '0.875rem',
    lg: '1rem',
    xl: '1.125rem',
  },
  lineHeight: {
    normal: '1.5',
    tight: '1.25',
  },
  colors: {
    primary: {
      900: '#071727',
      800: '#0d253f',
      700: '#12345a',
      base: '#1b4d8e',
      500: '#2563eb',
      300: '#60a5fa',
      200: '#a2cafa',
      100: '#bfdbfe',
      50: '#eff6ff',
    },
    neutral: {
      900: '#111827',
      800: '#1f2937',
      700: '#374151',
      base: '#4b5563',
      500: '#6b7280',
      400: '#9ca3af',
      300: '#d1d5db',
      200: '#eaecf0',
      100: '#f3f4f6',
      50: '#ffffff',
    },
    success: { base: '#059669', 50: '#ecfdf5' },
    danger: { base: '#dc2626', 50: '#fef2f2' },
    warning: { base: '#d97706', 50: '#fffbeb' },
  },
};

export const dasarVariablesTypography = {
  fontSans: dasarVariables.font.sans,
  fontHero: dasarVariables.font.hero,
  fontWeightRegular: dasarVariables.fontWeight.regular,
  fontWeightMedium: dasarVariables.fontWeight.medium,
  fontWeightSemibold: dasarVariables.fontWeight.semibold,
  fontWeightBold: dasarVariables.fontWeight.bold,
  fontSizeXss: dasarVariables.fontSize.xss,
  fontSizeXs: dasarVariables.fontSize.xs,
  fontSizeSm: dasarVariables.fontSize.sm,
  fontSizeBase: dasarVariables.fontSize.base,
  fontSizeLg: dasarVariables.fontSize.lg,
  fontSizeXl: dasarVariables.fontSize.xl,
  lineHeightNormal: dasarVariables.lineHeight.normal,
  lineHeightTight: dasarVariables.lineHeight.tight,
};
